// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_Erickson.Models;

#nullable disable

namespace Mission6_Erickson.Migrations
{
    [DbContext(typeof(MovieCollectionContext))]
    [Migration("20260214010249_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Mission06_Erickson.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Fantasy",
                            Director = "John Musker",
                            Rating = "PG",
                            Title = "Hercules",
                            Year = 1997
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action",
                            Director = "Jon Turteltaub",
                            Rating = "PG",
                            Title = "National Treasure",
                            Year = 2004
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Action",
                            Director = "Ruben Fleischer",
                            Rating = "PG-13",
                            Title = "Uncharted",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
